### ISSUE TITLE
Some Reddit pages can't be parsed

### ISSUE THREAD

**Issue by charleshope** [charleshope/opengrape#2]
The Reddit page [Girl relentlessly hitting her bf](https://www.reddit.com/r/PublicFreakout/comments/v6vob9/girl_relentlessly_hitting_her_bf/) can be parsed for its metadata, but the page [Finland's prime minister Sanna Marin is facing backlash after this video](https://www.reddit.com/r/PublicFreakout/comments/wrkily/finlands_prime_minister_sanna_marin_is_facing/) returns only nulls.

**Comment by kientux** [comment]
Missing `User-Agent` header is the reason 😬

**Comment by charleshope** [comment]
> Missing `User-Agent` header is the reason 😬

Thanks for the fix! What's odd is that it didn't always fail. Sometimes it worked, but randomly it failed.
